#!/bin/bash

echo -e "install start..."
sudo yum install epel-release -y -q
yum install figlet -y -q
figlet -ck "made    by    Eric"
sleep 1

read -p "Please input your account: " account
read -p "Please input your password: " password




sudo yum install python36 -y
python3 -m ensurepip
sudo pip3 install --upgrade pip
sudo pip3 install selenium
sudo yum install https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm -y
wget https://chromedriver.storage.googleapis.com/80.0.3987.106/chromedriver_linux64.zip
unzip chromedriver_linux64.zip
mv ~/auto_kx/chromedriver ~/
mv ~/auto_kx/auto_selenium.py ~/
chmod 777 /root/chromedriver
chmod 777 /root/auto_selenium.py



echo ${account} > /root/file1
echo ${password} > /root/file2

chmod 777 /root/file1
chmod 777 /root/file2

echo "0 18 * * 1-7 export DISPLAY=:0 && /usr/bin/python3 /root/auto_selenium.py" >> /etc/crontab

systemctl restart crond
systemctl enable crond

figlet -k "complete"
